//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess_EF.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCurrency
    {
        public TblCurrency()
        {
            this.TblOrders = new HashSet<TblOrder>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string country { get; set; }
    
        public virtual ICollection<TblOrder> TblOrders { get; set; }
    }
}
